apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-file
  namespace: {{ .Values.namespace }}
data:
  config.toml: |
    [network.client]
    server_address = "{{ .Values.server.address }}"

    {{- range $k, $v := .Values.hosts }}
    [{{ $k }}.integration]
    scheme = "host"

    [{{ $k }}.integration.host]
    url = "{{ $v.url }}"

    [{{ $k }}.integration.host.endpoints]
    {{- if $v.endpoints.entrypoint }}
    entrypoint = "{{ $v.endpoints.entrypoint }}"
    {{- end }}
    {{- if $v.endpoints.api }}
    api = "{{ $v.endpoints.api }}"
    {{- end }}

    [{{ $k }}.authorization.oauth2.client]
    {{- if $v.oauth2.clientId }}
    id = "{{ $v.oauth2.clientId }}"
    {{- end }}
    redirect_url = "{{ $.Values.server.oauth2.clientRedirectUrl }}"
    {{- end}}
