apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "rds.fullname" . }}-frontend-config
    namespace: {{ .Values.namespace }}
data:
    config.toml: |
        [general]
        {{ if .Values.frontend.supportEmail }}
        support_email = {{ .Values.frontend.supportEmail | quote }}
        {{- end }}

        [network.client]
        server_address = {{ include "rds.serverAddress" . | quote }}

        {{ range $k, $v := .Values.tenants }}
        [{{ lower $k }}.integration]
        scheme = {{ required (printf "Missing scheme for tenant %s" $k) $v.scheme | quote }}

        {{ if eq (lower $v.scheme) "host" -}}
        [{{ lower $k }}.integration.host]
        url = {{ required (printf "Missing URL for tenant %s" $k) $v.url | quote }}
        {{- end }}

        {{ if $v.oauth2 -}}
        [{{ lower $k }}.authorization.oauth2.client]
        id = {{ required (printf "Missing OAuth2 client ID for tenant %s" $k) $v.oauth2.clientId | quote }}
        redirect_url = {{ $v.url | quote }}
        {{- end }}
        {{ end }}
