apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-config-file
data:
    config.toml: |
        [network.client]
        server_address = "{{ .Values.server.address }}"
        
        [integration]
        scheme = "host"
        
        [integration.host]
        url = "{{ .Values.frontend.integration.hostUrl }}"
        
        [integration.host.endpoints]
        entrypoint = "{{ .Values.frontend.integration.endpoints.entrypoint }}"
        api = "{{ .Values.frontend.integration.endpoints.api }}"
        
        [authorization.oauth2.client]
        id = "{{ .Values.frontend.integration.clientId }}"
        redirect_url = "{{ .Values.server.oauth2.clientRedirectUrl }}"

