[network.client]
server_address = "http://localhost:4200"

[default.integration]
scheme = "host"

[default.integration.host]
url = "http://localhost:8080/apps/rdsng"

[default.authorization.oauth2.client]
id = "some_id"
redirect_url = "http://localhost:8080/apps/rdsng"
