apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "rds.fullname" . }}-domo-config
    namespace: {{ include "rds.namespace" . }}
data:
    {{- include "rds.generalSettings" . | indent 4 }}
    {{- include "rds.clientSettings" . | indent 4 }}
