{{- if .Values.domo.ingress.enabled -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.appName }}-domo-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.domo.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.domo.ingress.class }}
  rules:
    - {{- if .Values.domo.ingress.hostname }}
      host: {{ .Values.domo.ingress.hostname }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: domo-service
                port:
                  number: 5500
  {{- if .Values.domo.ingress.tls }}
  tls:
    {{ toYaml .Values.domo.ingress.tls | nindent 4 }}
  {{- end }}
  {{- end -}}
