apiVersion: v1
kind: ConfigMap
metadata:
    name: domo-config
    namespace: {{ .Values.namespace }}
data:
    RDS_GENERAL_DEBUG: {{ .Values.debugLog | quote }}
    RDS_GENERAL_DEBUG_TRACE: {{ .Values.debugTrace | quote }}
