apiVersion: v1
kind: Service
metadata:
    name: {{ include "rds.fullname" . }}-domo-service
    namespace: {{ include "rds.namespace" . }}
    labels: {{- include "rds.labels" (list . "domo") | nindent 8 }}
spec:
    selector:
        {{- include "rds.selectorLabels" (list . "domo") | nindent 8 }}
    ports:
        -   protocol: TCP
            port: 5500
            targetPort: 6969
