apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.connectors.stub.componentName }}-config"
  namespace: {{ .Values.nameSpace }}
data:
{{- if .Values.createSecrets }}
  RDS_NETWORK_API_KEY: {{ .Values.server.networkApiKey }}
{{- end }}
  RDS_NETWORK_EXTERNAL_REQUESTS_TIMEOUT: {{ default "" .Values.server.externalRequestsTimeout  | quote }}
  RDS_NETWORK_SERVER_ALLOWED_ORIGINS: {{ .Values.server.allowedOrigins }}
  RDS_AUTHORIZATION_OAUTH2_CLIENT_REDIRECT_URL: {{ .Values.server.oauth2.clientRedirectUrl }}
  RDS_AUTHORIZATION_OAUTH2_CLIENT_ID: {{ .Values.server.oauth2.clientId }}
  RDS_NETWORK_CLIENT_SERVER_ADDRESS: {{ .Values.server.address }}
