[connector]
target = "https://demo.dataverse.org/api/"

[authorization]
strategy = "bearer"

[authorization.bearer]
bearer_label = "API Token"
help_link = "https://guides.dataverse.org/en/latest/api/auth.html"
