from typing import Protocol


class Logger(Protocol):
    """ This protocol defines the general interfaces for our extended loggers. """
    def debug(self, msg: str, *, scope: str | None = None, **kwargs) -> None: ...
    def info(self, msg: str, *, scope: str | None = None, **kwargs) -> None: ...
    def warning(self, msg: str, *, scope: str | None = None, **kwargs) -> None: ...
    def error(self, msg: str, *, scope: str | None = None, **kwargs) -> None: ...
