{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.connectors.zenodo.componentName }}-secret"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RDS_AUTHORIZATION_OAUTH2_CLIENT_SECRET: {{ .Values.connectors.zenodo.oauth2.clientSecret }}
{{- end }}
