[network.client]
server_address = "http://rds-server-1:6969"

[authorization]
strategy = "oauth2"

[authorization.oauth2.server]
host = "https://sandbox.zenodo.org"
authorization_endpoint = "/oauth/authorize"
token_endpoint = "/oauth/token"
scope = "deposit:write deposit:actions"

[transmission]
max_attempts = 5
attempts_delay = 15.0
