{{- if .Values.createSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.connectors.osf.componentName }}-secret"
  namespace: {{ .Values.namespace }}
data:
  RDS_AUTHORIZATION_OAUTH2_CLIENT_SECRET: {{ .Values.connectors.osf.oauth2.clientSecret }}
{{- end }}
