# Docker compose file to build/run the entire components stack in development mode
# Note that the local source tree is mounted into the containers so that changes are applied automagically
services:
    # -- Base images --
    # Build-only Python base image
    py-base:
        image: rds-ng/py-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node-base:
        image: rds-ng/node-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Gate service
    gate:
        image: rds-ng/gate:develop
        volumes:
            -   type: bind
                source: ../../src
                target: /component
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "gate"
        depends_on:
            - py-base
        ports:
            - "4200:6969"
        environment:
            - RDS_NETWORK_SERVER_ALLOWED_ORIGINS=*

    # Web frontend
    frontend:
        image: rds-ng/frontend:develop
        volumes:
            -   type: bind
                source: ../../src/frontend/src
                target: /app/frontend/src
            -   type: bind
                source: ../../src/common
                target: /app/common
        build:
            context: ../../
            dockerfile: deployment/containers/web-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "frontend"
        depends_on:
            - node-base
        ports:
            - "8000:6969"
        environment:
            - RDS_NETWORK_CLIENT_SERVER_ADDRESS=http://localhost:4200
            - RDS_FRONTEND_AUTHENTICATION_SCHEME=basic
            - RDS_FRONTEND_HOST_API_URL=http://localhost:8080/apps/rdsng/api/
