# Docker Compose file to build entire components stack in Development mode
services:
    # -- Base images --
    # Build-only Python base image
    py_base:
        image: rds-ng/py-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node_base:
        image: rds-ng/node-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Server service
    server:
        image: rds-ng/server:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "server"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: OSF
    connector-osf:
        image: rds-ng/connector-osf:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/osf"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Zenodo
    connector-zenodo:
        image: rds-ng/connector-zenodo:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/zenodo"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: datasafe
    connector-datasafe:
        image: rds-ng/connector-datasafe:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/inveniordm"
                COMPONENT_ADDITIONAL_LOCATION: "connectors/datasafe"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: datastore
    connector-datastore:
        image: rds-ng/connector-datastore:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/inveniordm"
                COMPONENT_ADDITIONAL_LOCATION: "connectors/datastore"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Dataverse
    connector-dataverse:
        image: rds-ng/connector-dataverse:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/dataverse"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Stub
    connector-stub:
        image: rds-ng/connector-stub:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "connectors/stub"
            additional_contexts:
                py_base: "service:py_base"

    # Domo
    domo:
        image: rds-ng/domo:develop
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "domo"
            additional_contexts:
                py_base: "service:py_base"

    # Web frontend
    frontend:
        image: rds-ng/frontend:develop
        build:
            context: ../../
            dockerfile: deployment/containers/web-component/dev.Dockerfile
            args:
                COMPONENT_NAME: "frontend"
            additional_contexts:
                node_base: "service:node_base"
