# Docker compose file to build/run the entire components stack in development mode
# Note that the local source tree is mounted into the containers so that changes are applied automagically
services:
    # Build-only Python base image
    py-base:
        image: rds-ng/py-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node-base:
        image: rds-ng/node-base:develop
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/dev.Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Gate service
    gate:
        image: rds-ng/gate:develop
        volumes:
            -   type: bind
                source: ../../src
                target: /component
        build:
            context: ../../
            dockerfile: deployment/containers/component/dev.Dockerfile
            args:
                COMPONENT_NAME: "gate"
        depends_on:
            - py-base
        ports:
            - "4200:6969"

    # Debug testing buddy
    testbuddy:
        image: rds-ng/testbuddy:develop
        volumes:
            -   type: bind
                source: ../../src
                target: /component
        build:
            context: ../../
            dockerfile: deployment/containers/component/dev.Dockerfile
            args:
                COMPONENT_NAME: "testbuddy"
        depends_on:
            - py-base
        ports:
            - "4300:6969"
        environment:
            - RDS_NETWORK_CLIENT_SERVER_ADDRESS=http://rds-gate-1:6969

    # Web frontend
    frontend:
        image: rds-ng/frontend:develop
        volumes:
            -   type: bind
                source: ../../src/web/frontend/src
                target: /app/web/frontend/src
            -   type: bind
                source: ../../src/common/web
                target: /app/common/web
        build:
            context: ../../
            dockerfile: deployment/containers/web/dev.Dockerfile
            args:
                WEB_NAME: "frontend"
        depends_on:
            - node-base
        ports:
            - "8000:6969"
