# Docker Compose file to build the entire components stack in Release mode
services:
    # -- Base images --
    # Build-only Python base image
    py_base:
        image: rds-ng/py-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node_base:
        image: rds-ng/node-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Server service
    server:
        image: rds-ng/server:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "server"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: OSF
    connector-osf:
        image: rds-ng/connector-osf:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/osf"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Zenodo
    connector-zenodo:
        image: rds-ng/connector-zenodo:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/zenodo"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: datasafe
    connector-datasafe:
        image: rds-ng/connector-datasafe:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/inveniordm"
                COMPONENT_ADDITIONAL_LOCATION: "connectors/datasafe"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: datastore
    connector-datastore:
        image: rds-ng/connector-datastore:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/inveniordm"
                COMPONENT_ADDITIONAL_LOCATION: "connectors/datastore"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Dataverse
    connector-dataverse:
        image: rds-ng/connector-dataverse:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/dataverse"
            additional_contexts:
                py_base: "service:py_base"

    # Connector: Stub
    connector-stub:
        image: rds-ng/connector-stub:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/stub"
            additional_contexts:
                py_base: "service:py_base"

    # Domo
    domo:
        image: rds-ng/domo:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "domo"
            additional_contexts:
                py_base: "service:py_base"

    # Web frontend
    frontend:
        image: rds-ng/frontend:latest
        build:
            context: ../../
            dockerfile: deployment/containers/web-component/Dockerfile
            args:
                COMPONENT_NAME: "frontend"
            additional_contexts:
                node_base: "service:node_base"
