# Docker compose file to build/run the entire components stack
services:
    # -- Base images --
    # Build-only Python py-base image
    py-base:
        image: rds-ng/py-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node-base:
        image: rds-ng/node-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Server service
    server:
        image: rds-ng/server:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "server"
        depends_on:
            - py-base
        ports:
            - "4200:6969"
        environment:
            - RDS_NETWORK_SERVER_ALLOWED_ORIGINS=*

    # Connector: OSF
    connector-psf:
        image: rds-ng/connector-osf:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/osf"
        depends_on:
            - py-base
        ports:
            - "4300:6969"
        environment:
            - RDS_NETWORK_SERVER_ALLOWED_ORIGINS=*

    # Connector: Stub
    connector-stub:
        image: rds-ng/connector-stub:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/stub"
        depends_on:
            - py-base
        ports:
            - "4400:6969"
        environment:
            - RDS_NETWORK_SERVER_ALLOWED_ORIGINS=*

    # Web frontend
    frontend:
        image: rds-ng/frontend:latest
        build:
            context: ../../
            dockerfile: deployment/containers/web-component/Dockerfile
            args:
                COMPONENT_NAME: "frontend"
        depends_on:
            - node-base
        ports:
            - "8000:80"
