# Docker compose file to build/run the entire components stack
services:
    # -- Base images --
    # Build-only Python py-base image
    py-base:
        image: rds-ng/py-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node-base:
        image: rds-ng/node-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Gate service
    gate:
        image: rds-ng/gate:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "gate"
        depends_on:
            - py-base
        ports:
            - "4200:6969"

    # Web frontend
    frontend:
        image: rds-ng/frontend:latest
        build:
            context: ../../
            dockerfile: deployment/containers/web-frontend/Dockerfile
            args:
                WEB_NAME: "frontend"
        depends_on:
            - node-base
        ports:
            - "8000:6969"
