# Docker compose file to build/run the entire components stack
services:
    # -- Base images --
    # Build-only Python base image
    py_base:
        image: rds-ng/py-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/py-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # Build-only Node base image
    node_base:
        image: rds-ng/node-base:latest
        build:
            context: ../../
            dockerfile: deployment/containers/node-base/Dockerfile
        deploy:
            mode: replicated
            replicas: 0

    # -- Component images --
    # Server service
    server:
        image: rds-ng/server:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "server"
            additional_contexts:
                py_base: "service:py_base"
        ports:
            - "4200:6969"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}server.env

    # Connector: OSF
    connector-osf:
        image: rds-ng/connector-osf:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/osf"
            additional_contexts:
                py_base: "service:py_base"
        ports:
            - "4300:6969"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}connector-osf.env

    # Connector: Zenodo
    connector-zenodo:
        image: rds-ng/connector-zenodo:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/zenodo"
            additional_contexts:
                py_base: "service:py_base"
        ports:
            - "4400:6969"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}connector-zenodo.env

    # Connector: datasafe
    connector-datasafe:
        image: rds-ng/connector-datasafe:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/inveniordm"
                COMPONENT_ADDITIONAL_LOCATION: "connectors/datasafe"
            additional_contexts:
                py_base: "service:py_base"
        ports:
            - "4500:6969"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}connector-datasafe.env

    # Connector: Stub
    connector-stub:
        image: rds-ng/connector-stub:latest
        build:
            context: ../../
            dockerfile: deployment/containers/backend-component/Dockerfile
            args:
                COMPONENT_NAME: "connectors/stub"
            additional_contexts:
                py_base: "service:py_base"
        ports:
            - "4900:6969"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}connector-stub.env

    # Web frontend
    frontend:
        image: rds-ng/frontend:latest
        volumes:
            -   type: bind
                source: ../config/frontend
                target: /app/config
        build:
            context: ../../
            dockerfile: deployment/containers/web-component/Dockerfile
            args:
                COMPONENT_NAME: "frontend"
            additional_contexts:
                node_base: "service:node_base"
        ports:
            - "8000:80"
        env_file:
            - ../env/${RDS_NG_BUILD_ENVIRONMENT_PREFIX:-}frontend.env
