{{ if and (hasKey .Values.connectors.dataverse "logos") (or (and (hasKey .Values.connectors.dataverse.logos "default") (.Files.Get .Values.connectors.dataverse.logos.default)) (and (hasKey .Values.connectors.dataverse.logos "horizontal") (.Files.Get .Values.connectors.dataverse.logos.horizontal))) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.connectors.dataverse.componentName }}-logos-config"
  namespace: {{ .Values.namespace }}

binaryData:
{{ if and (hasKey .Values.connectors.dataverse "logos") (hasKey .Values.connectors.dataverse.logos "default") }}
  logo.png: |-
    {{ .Files.Get .Values.connectors.dataverse.logos.default  | b64enc  }}
{{ end }}
{{ if and (hasKey .Values.connectors.dataverse "logos") (hasKey .Values.connectors.dataverse.logos "horizontal") }}
  horizontal.png: |-
    {{ .Files.Get .Values.connectors.dataverse.logos.horizontal  | b64enc  }}
{{ end }}
{{ end }}
