# bridgit (RDS-NG) Helm values
# ----------------------------
#
# The following values are mandatory and must be set properly:
#  - network.apiKey
#  - server.ingress.hostname
#  - domo.ingress.hostname
#  - frontend.ingress.hostname
#
# All tenants (i.e., hosts running an integrated frontend) must also be configured properly under the "tenants" section.
# For each tenant, the following values must be set:
#  - tenants.<tenantid>.scheme
#  - tenants.<tenantid>.url
#
# Depending on your environment, you'll most likely need to set further values properly.
#

nameOverride: ""    # Override the application name (defaults to "rds")
namespace: ""       # Override the application namespace

image:
    host: "ghcr.io/sciebo-rds"      # The image host; do not append a slash (e.g., ghcr.io/sciebo-rds instead of ghcr.io/sciebo-rds/)
    tag: "latest"                   # The image tag
    pullPolicy: "always"            # The image pull policy

debug:
    enabled: false          # Whether to run in debug mode, resulting in more textual output and fewer restrictions
    enableTracing: false    # Whether to log function calls for extensive debugging

network:
    apiKey: ""  # An arbitrary API key to access protected resources; this must always be provided

server:
    volume:
        storageSize: "1Gi"              # The size to allocate for the main server volume
        storageClassName: "standard"    # The storage class for the main server volume
    storage:
        driver: "memory"                # The storage driver to use; can either be "memory" for a volatile in-memory storage or "database" for persistency
        database:                       # Database-specific settings; only effective if driver is set to "database"
            engine: "sqlite"            # The type of database to use; currently supported are: sqlite, postgresql, mysql or mariadb
            sqlite:
                file: "/data/rds.db"    # The file SQLite stores its data in
            postgresql:
                host: ""                # The database host; required if this engine is used
                port: 5432              # The database port
                database: "rds-ng"      # The database name
                user: ""                # The username; required if this engine is used
                password: ""            # The user's password; required if this engine is used
            mysql:
                host: ""                # The database host; required if this engine is used
                port: 3306              # The database port
                database: "rds-ng"      # The database name
                user: ""                # The username; required if this engine is used
                password: ""            # The user's password; required if this engine is used
            mariadb:
                host: ""                # The database host; required if this engine is used
                port: 3306              # The database port
                database: "rds-ng"      # The database name
                user: ""                # The username; required if this engine is used
                password: ""            # The user's password; required if this engine is used
    ingress:
        hostname: ""        # The hostname (without any scheme); required
        annotations: {}     # A list of key-value pairs to pass as annotations
        class: ""           # The ingress controller class
        path: "/"           # The ingress root path
        pathType: ""        # The root path type
        tlsSecret: ""       # If specified, enable TLS and use this secret (must be created manually upfront)

domo:
    ingress:
        hostname: ""        # The hostname (without any scheme); required
        annotations: {}     # A list of key-value pairs to pass as annotations
        class: ""           # The ingress controller class
        path: "/"           # The ingress root path
        pathType: ""        # The root path type
        tlsSecret: ""       # If specified, enable TLS and use this secret (must be created manually upfront)

frontend:
    ingress:
        hostname: ""        # The hostname (without any scheme); required
        annotations: {}     # A list of key-value pairs to pass as annotations
        class: ""           # The ingress controller class
        path: "/"           # The ingress root path
        pathType: ""        # The root path type
        tlsSecret: ""       # If specified, enable TLS and use this secret (must be created manually upfront)

tenants:
    # All tenants (i.e., hosts running an integrated frontend) must be configured individually by listing each using its assigned identifier
    default:                    # The identifier as specified in the corresponding integration app
        scheme: "host"          # The integration scheme/type (only "host" is currently supported)
        url: ""                 # The full URL of the host (including its scheme and path)
        oauth2:                 # Leave this block out if the host doesn't use OAuth2
            clientId: ""        # The OAuth2 client id
            clientSecret: ""    # The OAuth2 client secret
