[connector]
target = "https://datastore.uni-muenster.de/api/"

[authorization]
strategy = "bearer"

[authorization.bearer]
bearer_label = "API Token"
help_link = "https://datastore.uni-muenster.de/faq"
