apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.connectors.dataverse.componentName }}-config"
  namespace: {{ .Values.namespace }}
data:
  RDS_CONNECTOR_TARGET: {{ .Values.connectors.dataverse.targetUrl }}
  RDS_NETWORK_SERVER_ALLOWED_ORIGINS: {{ .Values.server.allowedOrigins }}
  RDS_NETWORK_CLIENT_SERVER_ADDRESS: {{ .Values.server.address }}
  RDS_GENERAL_DEBUG: {{ .Values.debugLog | quote }}
  RDS_GENERAL_DEBUG_TRACE: {{ .Values.debugTrace | quote }}
