events {}

http {
    # Nextcloud
    server {
        listen 443 ssl;
        server_name nextcloud.dev.local;

        ssl_certificate     /etc/nginx/certs/local.crt;
        ssl_certificate_key /etc/nginx/certs/local.key;

        location / {
            include location.snippet.conf;

            add_header 'Access-Control-Allow-Origin' 'https://bridgit.nextcloud.dev.local' always;
            proxy_pass http://nextcloud:80;
        }
    }

    # Server
    server {
        listen 4200 ssl;
        server_name bridgit.nextcloud.dev.local;

        ssl_certificate     /etc/nginx/certs/local.crt;
        ssl_certificate_key /etc/nginx/certs/local.key;

        location / {
            include location.snippet.conf;

            add_header 'Access-Control-Allow-Origin' 'https://bridgit.nextcloud.dev.local' always;
            proxy_pass http://rds-server:6969;
        }
    }

    # Domo
    server {
        listen 5500 ssl;
        server_name bridgit.nextcloud.dev.local;

        ssl_certificate     /etc/nginx/certs/local.crt;
        ssl_certificate_key /etc/nginx/certs/local.key;

        location / {
            include location.snippet.conf;

            add_header 'Access-Control-Allow-Origin' 'https://nextcloud.dev.local' always;
            proxy_pass http://rds-domo:6969;
        }
    }

    # Frontend
    server {
        listen 443 ssl;
        server_name bridgit.nextcloud.dev.local;

        ssl_certificate     /etc/nginx/certs/local.crt;
        ssl_certificate_key /etc/nginx/certs/local.key;

        location / {
            include location.snippet.conf;

            add_header 'Access-Control-Allow-Origin' 'https://nextcloud.dev.local' always;
            proxy_pass http://rds-frontend:6969;
        }
    }
}
