{{- if .Values.createSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: network-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  RDS_NETWORK_API_KEY: {{ .Values.server.networkApiKey | quote }}
{{- end }}
