apiVersion: v1
kind: Service
metadata:
    name: {{ include "rds.fullname" . }}-server-service
    namespace: {{ include "rds.namespace" . }}
    labels: {{- include "rds.labels" . | nindent 8 }}
spec:
    selector:
        {{- include "rds.selectorLabels" . | nindent 8 }}
    ports:
        -   protocol: TCP
            port: 4200
            targetPort: 6969
