{{- if .Values.createSecrets -}}
apiVersion: v1
kind: Secret
metadata:
    name: server-secret
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    {{- range $k, $v := .Values.hosts }}
    {{- if $v.oauth2.hostSecret }}
    RDS_{{ $k | upper }}_AUTHORIZATION_OAUTH2_SECRETS_HOST: {{ $v.oauth2.hostSecret | quote }}
    {{- end }}
    {{- end }}
{{- end }}
