{{- if .Values.createSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
stringData:
  RDS_AUTHORIZATION_OAUTH2_SECRETS_HOST: {{ .Values.server.oauth2.hostSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_OSF: {{ .Values.connectors.osf.oauth2.clientSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_ZENODO: {{ .Values.connectors.zenodo.oauth2.clientSecret }}
  RDS_AUTHORIZATION_OAUTH2_SECRETS_STUB: {{ .Values.connectors.stub.oauth2.clientSecret }}
{{- end }}
