apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "rds.fullname" . }}-server-config
    namespace: {{ include "rds.namespace" . }}
data:
    {{- include "rds.generalSettings" . | indent 4 }}
    RDS_STORAGE_DRIVER: {{ default "memory" .Values.server.storage.driver | quote }}

    {{- if eq (lower .Values.server.storage.driver) "database" }}
    RDS_STORAGE_DATABASE_ENGINE: {{ default "sqlite" .Values.server.storage.database.engine | quote }}

    {{- if eq (lower .Values.server.storage.database.engine) "sqlite" }}
    RDS_STORAGE_DATABASE_SQLITE_FILE: {{ default "/data/rds.db" .Values.server.storage.database.sqlite.file | quote }}
    {{- else if eq (lower .Values.server.storage.database.engine) "postgresql" }}
    {{ include "rds.database.settings" (list .Values.server.storage.database.postgresql "PostgreSQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mysql" }}
    {{ include "rds.database.settings" (list .Values.server.storage.database.mysql "MySQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mariadb" }}
    {{ include "rds.database.settings" (list .Values.server.storage.database.mariadb "MariaDB") | nindent 4 }}
    {{- end }}

    {{- end }}
