apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ include "rds.fullname" . }}-server-pvc
    namespace: {{ include "rds.namespace" . }}
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.server.volume.storageSize | default "1Gi" }}
    storageClassName: {{ .Values.server.volume.storageClassName | default "standard" }}
