apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "rds.fullname" . }}-server
    namespace: {{ include "rds.namespace" . }}
    labels: {{- include "rds.labels" (list . "server") | nindent 8 }}
spec:
    replicas: 1
    selector:
        matchLabels: {{- include "rds.selectorLabels" (list . "server") | nindent 12 }}
    template:
        metadata:
            labels: {{- include "rds.selectorLabels" (list . "server") | nindent 16 }}
        spec:
            containers:
                -   name: {{ include "rds.fullname" . }}-server
                    {{- include "rds.image" (list . "rds-ng-server") | nindent 20 }}
                    ports:
                        -   containerPort: 6969
                    volumeMounts:
                        {{- if include "rds.server.needsVolume" . }}
                        -   mountPath: /data
                            name: {{ include "rds.fullname" . }}-server-volume
                        {{- end }}
                        -   mountPath: /component/server/.config
                            name: {{ include "rds.fullname" . }}-server-tenants-config-volume
                    envFrom:
                        -   secretRef:
                                name: {{ include "rds.fullname" . }}-network-api-secret
                        -   configMapRef:
                                name: {{ include "rds.fullname" . }}-server-config
                        -   secretRef:
                                name: {{ include "rds.fullname" . }}-server-config-secret
                        -   secretRef:
                                name: {{ include "rds.fullname" . }}-server-tenants-config-secret
            restartPolicy: Always
            volumes:
                {{- if include "rds.server.needsVolume" . }}
                -   name: {{ include "rds.fullname" . }}-server-volume
                    persistentVolumeClaim:
                        claimName: {{ include "rds.fullname" . }}-server-pvc
                {{- end }}
                -   name: {{ include "rds.fullname" . }}-server-tenants-config-volume
                    configMap:
                        name: {{ include "rds.fullname" . }}-server-tenants-config
