apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rds.fullname" . }}-server-config-secret
    namespace: {{ include "rds.namespace" . }}
type: Opaque
stringData:
    {{- if eq (lower .Values.server.storage.driver) "database" }}

    {{- if eq (lower .Values.server.storage.database.engine) "postgresql" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.postgresql "PostgreSQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mysql" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.mysql "MySQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mariadb" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.mariadb "MariaDB") | nindent 4 }}
    {{- end }}

    {{- end }}

    {{ range $k, $v := .Values.tenants -}}
    {{ if $v.oauth2 -}}
    RDS_TENANT_{{- upper $k -}}_AUTHORIZATION_OAUTH2_CLIENT_SECRET: {{ required (printf "Missing OAuth2 client secret for tentant %s" $k) $v.oauth2.clientSecret | quote }}
    {{- end }}
    {{- end }}
