apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rds.fullname" . }}-server-tenants-config-secret
    namespace: {{ include "rds.namespace" . }}
type: Opaque
stringData:
    {{ range $k, $v := .Values.tenants -}}
    {{ if $v.oauth2 -}}
    RDS_TENANT_{{- upper $k -}}_AUTHORIZATION_OAUTH2_CLIENT_SECRET: {{ required (printf "Missing OAuth2 client secret for tenant %s" $k) $v.oauth2.clientSecret | quote }}
    {{- end }}
    {{- end }}
