{{- if .Values.createSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.hosts }}
  {{- if $v.oauth2.hostSecret }}
  RDS_{{ $k | upper }}_AUTHORIZATION_OAUTH2_SECRETS_HOST: {{ $v.oauth2.hostSecret | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.server.storage.engine "postgresql" }}
  RDS_STORAGE_DATABASE_POSTGRESQL_PASSWORD: {{ .Values.server.storage.postgresql.password | quote }}
  {{- end }}
  {{- if eq .Values.server.storage.engine "mysql" }}
  RDS_STORAGE_DATABASE_MYSQL_PASSWORD: {{ .Values.server.storage.mysql.password | quote }}
  {{- end }}
  {{- if eq .Values.server.storage.engine "mariadb" }}
  RDS_STORAGE_DATABASE_MARIADB_PASSWORD: {{ .Values.server.storage.mariadb.password | quote }}
  {{- end }}
{{- end }}
