{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rds.fullname" . }}-server-config-secret
    namespace: {{ include "rds.namespace" . }}
type: Opaque
stringData:
    {{- if eq (lower .Values.server.storage.driver) "database" }}

    {{- if eq (lower .Values.server.storage.database.engine) "postgresql" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.postgresql "PostgreSQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mysql" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.mysql "MySQL") | nindent 4 }}
    {{- else if eq (lower .Values.server.storage.database.engine) "mariadb" }}
    {{ include "rds.database.secrets" (list .Values.server.storage.database.mariadb "MariaDB") | nindent 4 }}
    {{- end }}

    {{- end }}
{{- end }}
