[connector]
target = "https://datasafe-staging.uni-muenster.de/api/"

[network.client]
server_address = "http://rds-server-1:6969"

[authorization]
strategy = "basic"

[authorization.basic]
user_id_label = "Username"
user_id_optional = true
user_password_label = "API Token"
user_password_optional = false
help_link = "https://datasafe-staging.uni-muenster.de/faq"
