import { type PropertyProfile, PropertyDataType } from "../PropertyProfile";

export const dataCite: PropertyProfile = {
    profile_id: { name: "DataCite", version: "4.5.0" },
    categories: [
        {
            id: "Mandatory",
            name: "Mandatory",
            description: "Mandatory DataCite properties",
            properties: [
                {
                    id: "Identifier",
                    name: "Identifier (DOI)",
                    type: PropertyDataType.STRING,
                    description:
                        "The Identifier is a unique string that identifies a resource. For software, determine whether the identifier is for a specific version of a piece of software, (per the Force11 Software Citation Principles) or for all versions. The format should be 10.21384/foo",
                    showAlways: true,
                    required: true,
                },
                {
                    id: "Creator",
                    name: "Creator",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "The main researchers involved in producing the data, or the authors of the publication, in priority order. To supply multiple creators, repeat this property.",
                    showAlways: true,
                    required: true,
                },
                {
                    id: "Title",
                    name: "Title",
                    type: PropertyDataType.STRING,
                    description:
                        "A name or title by which a resource is known. May be the title of a dataset or the name of a piece of software or an instrument.",
                    showAlways: true,
                    required: true,
                },
                {
                    id: "Publisher",
                    name: "Publisher",
                    type: PropertyDataType.STRING,
                    description:
                        "The name of the entity that holds, archives, publishes, prints, distributes, releases, issues, or produces the resource. This property will be used to formulate the citation, so consider the prominence of the role.",
                    showAlways: true,
                    required: true,
                },
                {
                    id: "PublicationYear",
                    name: "Publication Year",
                    type: PropertyDataType.NUMBER,
                    description:
                        "The year when the data was or will be made publicly available. In the case of resources such as software or dynamic data where there may be multiple releases in one year, include the Date property and sub-properties (dateType/dateInformation) to provide more information about the publication or release date details. Format: YYYY.",
                    showAlways: true,
                    required: true,
                },
                {
                    id: "RessourceType",
                    name: "Ressource Type",
                    type: PropertyDataType.STRING,
                    description:
                        "Free text. The recommended content is a single term of some detail so that a pair can be formed with the resourceTypeGeneral sub-property. For example, a resourceType of “Census Data” paired with a resourceTypeGeneral of “Dataset” yields “Dataset/Census Data”.",
                    showAlways: true,
                    required: true,
                },
            ],
        },
        {
            id: "Recommended",
            name: "Recommended ",
            description: "Properties recommended by DataCite",
            properties: [
                {
                    id: "Subject",
                    name: "Subject",
                    type: PropertyDataType.STRINGLIST,
                    description: "Subject, keyword, classification code, or key phrase describing the resource.",
                    showAlways: false,
                    required: false,
                },
                {
                    id: "Contributor",
                    name: "Contributor",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "The institution or person responsible for collecting, managing, distributing, or otherwise contributing to the development of the resource. To supply multiple contributors, repeat this property. For software, if there is an alternate entity that “holds, archives, publishes, prints, distributes, releases, issues, or produces” the code, use the contributorType “hostingInstitution” for the code repository. For instruments, if there is an institution responsible for the management of the instrument (for example, the legal owner, the operator, or an institute providing access to the instrument), use the contributorType “hostingInstitution” for the owner of the instrument.",
                    showAlways: false,
                    required: false,
                },
                {
                    id: "Date",
                    name: "Date",
                    type: PropertyDataType.DATE,
                    description:
                        "YYYY, YYYY-MM-DD, YYYY- MM-DDThh:mm:ssTZD or any other format or level of granularity described in W3CDTF. Use RKMS-ISO8601 standard for depicting date ranges. Example: 2004-03-02/2005- 06-02. Years before 0000 must be prefixed with a - sign, e.g., -0054 to indicate 55 BC.",
                    showAlways: false,
                    required: false,
                },
                {
                    id: "RelatedIdentifier",
                    name: "Related Identifiers",
                    type: PropertyDataType.STRINGLIST,
                    description: "Identifiers of related resources. These must be globally unique identifiers.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "Description",
                    name: "Description",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "All additional information that does not fit in any of the other categories. May be used for technical information or detailed information associated with a scientific instrument.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "GeoLocation",
                    name: "GeoLocation",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "Spatial region or named place where the data was gathered or about which the data is focused. Repeat this property to indicate several different locations.",
                    showAlways: true,
                    required: false,
                },
            ],
        },
        {
            id: "Optional",
            name: "Optional",
            description: "Optional properties",
            properties: [
                {
                    id: "Language",
                    name: "Language",
                    type: PropertyDataType.DROPDOWN,
                    description: "The primary language of the resource.",
                    showAlways: false,
                    required: false,
                    options: [
                        "ab",
                        "aa",
                        "af",
                        "ak",
                        "sq",
                        "am",
                        "ar",
                        "an",
                        "hy",
                        "as",
                        "av",
                        "ae",
                        "ay",
                        "az",
                        "bm",
                        "ba",
                        "eu",
                        "be",
                        "bn",
                        "bh",
                        "bi",
                        "bs",
                        "br",
                        "bg",
                        "my",
                        "ca",
                        "km",
                        "ch",
                        "ce",
                        "ny",
                        "zh",
                        "cu",
                        "cv",
                        "kw",
                        "co",
                        "cr",
                        "hr",
                        "cs",
                        "da",
                        "dv",
                        "nl",
                        "dz",
                        "en",
                        "eo",
                        "et",
                        "ee",
                        "fo",
                        "fj",
                        "fi",
                        "fr",
                        "ff",
                        "gd",
                        "gl",
                        "lg",
                        "ka",
                        "de",
                        "ki",
                        "el",
                        "kl",
                        "gn",
                        "gu",
                        "ht",
                        "ha",
                        "he",
                        "hz",
                        "hi",
                        "ho",
                        "hu",
                        "is",
                        "io",
                        "ig",
                        "id",
                        "ia",
                        "ie",
                        "iu",
                        "ik",
                        "ga",
                        "it",
                        "ja",
                        "jv",
                        "kn",
                        "kr",
                        "ks",
                        "kk",
                        "rw",
                        "kv",
                        "kg",
                        "ko",
                        "kj",
                        "ku",
                        "ky",
                        "lo",
                        "la",
                        "lv",
                        "lb",
                        "li",
                        "ln",
                        "lt",
                        "lu",
                        "mk",
                        "mg",
                        "ms",
                        "ml",
                        "mt",
                        "gv",
                        "mi",
                        "mr",
                        "mh",
                        "ro",
                        "mn",
                        "na",
                        "nv",
                        "nd",
                        "ng",
                        "ne",
                        "se",
                        "no",
                        "nb",
                        "nn",
                        "ii",
                        "oc",
                        "oj",
                        "or",
                        "om",
                        "os",
                        "pi",
                        "pa",
                        "ps",
                        "fa",
                        "pl",
                        "pt",
                        "qu",
                        "rm",
                        "rn",
                        "ru",
                        "sm",
                        "sg",
                        "sa",
                        "sc",
                        "sr",
                        "sn",
                        "sd",
                        "si",
                        "sk",
                        "sl",
                        "so",
                        "st",
                        "nr",
                        "es",
                        "su",
                        "sw",
                        "ss",
                        "sv",
                        "tl",
                        "ty",
                        "tg",
                        "ta",
                        "tt",
                        "te",
                        "th",
                        "bo",
                        "ti",
                        "to",
                        "ts",
                        "tn",
                        "tr",
                        "tk",
                        "tw",
                        "ug",
                        "uk",
                        "ur",
                        "uz",
                        "ve",
                        "vi",
                        "vo",
                        "wa",
                        "cy",
                        "fy",
                        "wo",
                        "xh",
                        "yi",
                        "yo",
                        "za",
                        "zu",
                    ],
                },
                {
                    id: "AlternateIdentifier",
                    name: "Alternate Identifier",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "An identifier other than the primary Identifier applied to the resource being registered. This may be any alphanumeric string which is unique within its domain of issue. May be used for local identifiers, a serial number of an instrument or an inventory number. The AlternateIdentifier should be an additional identifier for the same instance of the resource (i.e., same location, same file).",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "Size",
                    name: "Size",
                    type: PropertyDataType.STRINGLIST,
                    description: "Size (e.g., bytes, pages, inches, etc.) or duration (extent), e.g., hours, minutes, days, etc., of a resource.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "Format",
                    name: "Format",
                    type: PropertyDataType.STRINGLIST,
                    description:
                        "Technical format of the resource. Use file extension or MIME type where possible, e.g., PDF, XML, MPG or application/pdf, text/xml, video/mpeg.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "Version",
                    name: "Format",
                    type: PropertyDataType.STRING,
                    description:
                        "The version number of the resource. Suggested practice: track major_version.minor_version. Register a new identifier for a major version change.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "Rights",
                    name: "Rights",
                    type: PropertyDataType.STRINGLIST,
                    description: "Any rights information for this resource. The property may be repeated to record complex rights characteristics.",
                    showAlways: true,
                    required: false,
                },
                {
                    id: "FundingReference",
                    name: "Funding Reference",
                    type: PropertyDataType.STRINGLIST,
                    description: "Information about financial support (funding) for the resource being registered.",
                    showAlways: true,
                    required: false,
                },
            ],
        },
    ],
};
