[network.server]
# idle_timeout = 5

[storage]
driver = "database"
default_root_path = "/files"

[storage.database]
engine = "mariadb"
dump_sql = false

[storage.database.sqlite]
file = "/data/rds.db"

[storage.database.mariadb]
host = "10.0.2.15"
user = "user"
password = "user"
