[network.server]
# idle_timeout = 5

[storage]
driver = "database"
default_root_path = "/files"

[storage.database]
engine = "mysql"
dump_sql = false

[storage.database.sqlite]
file = "/data/rds.db"

[storage.database.mysql]
host = "10.0.2.15"
user = "test"
password = "test"
