[network.client]
server_address = "http://localhost:4200"

[integration]
scheme = "host"

[integration.host]
url = "http://localhost:8080/apps/rdsng/"

[authorization.oauth2.client]
id = "some_key"
redirect_url = "http://localhost:8080/apps/rdsng/"
