[network.client]
server_address = "http://localhost:4200"

[default.integration]
scheme = "host"

[default.integration.host]
url = "http://localhost:8080/apps/rdsng"

[default.authorization.oauth2.client]
id = "ykyX7aWa19uL6Y3B0M5ajg8t0WGxVai1wOgJsYRmGDyFWjUgjVQs3tZDdeO4V1K4"
redirect_url = "http://localhost:8080/apps/rdsng"
