{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rds.fullname" . }}-network-api-secret
    namespace: {{ include "rds.namespace" . }}
type: Opaque
stringData:
    RDS_NETWORK_API_KEY: {{ (required "No API key specified" .Values.network.apiKey) | quote }}
{{- end }}
