apiVersion: v1
kind: Secret
metadata:
    name: {{ include "rds.fullname" . }}-network-api-secret
    namespace: {{ include "rds.namespace" . }}
type: Opaque
stringData:
    RDS_NETWORK_API_KEY: {{ required "A network API key must be specified" .Values.network.apiKey | quote }}
