name: Python Type Checks and Linting

on: [pull_request, push]

env:
  SCRIPTS_DIR: scripts

jobs:
  type_check_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pytype>=2023.5.24"
          if [ -f ./deployment/containers/py-base/requirements.txt ]; then pip install -r ./deployment/containers/py-base/requirements.txt; fi
      - name: Check Types with pytype
        run: |
          python ${{ env.SCRIPTS_DIR }}/run-typechecks.py